using System.Text.Json.Serialization;

namespace LifeRelier.Infrastructure.AI.Models;

/// <summary>
/// Google AI Studio Gemini API Request Payload matching the latest REST API specification.
/// </summary>
public class GeminiApiRequest
{
    /// <summary>
    /// Gets or sets the system instruction block for setting persona and rules.
    /// </summary>
    [JsonPropertyName("system_instruction")]
    public GeminiContent? SystemInstruction { get; set; }

    /// <summary>
    /// Gets or sets the list of content turns (messages) in the conversation.
    /// </summary>
    [JsonPropertyName("contents")]
    public List<GeminiContent> Contents { get; set; } = [];

    /// <summary>
    /// Gets or sets model generation parameters (temperature, responseMimeType, etc.).
    /// </summary>
    [JsonPropertyName("generationConfig")]
    public GeminiGenerationConfig? GenerationConfig { get; set; }

    /// <summary>
    /// Gets or sets optional safety settings filters.
    /// </summary>
    [JsonPropertyName("safetySettings")]
    public List<GeminiSafetySetting>? SafetySettings { get; set; }
}

/// <summary>
/// Represents content blocks (turns or instructions) in Gemini API payload.
/// </summary>
public class GeminiContent
{
    /// <summary>
    /// Gets or sets the role of the message sender (e.g., "user", "model").
    /// </summary>
    [JsonPropertyName("role")]
    public string? Role { get; set; }

    /// <summary>
    /// Gets or sets the list of content parts (e.g. text blocks).
    /// </summary>
    [JsonPropertyName("parts")]
    public List<GeminiPart> Parts { get; set; } = [];
}

/// <summary>
/// Represents individual content part payload containing text or inline data.
/// </summary>
public class GeminiPart
{
    /// <summary>
    /// Gets or sets the text content string.
    /// </summary>
    [JsonPropertyName("text")]
    public string Text { get; set; } = string.Empty;
}

/// <summary>
/// Gemini API Generation Configuration parameters.
/// </summary>
public class GeminiGenerationConfig
{
    /// <summary>
    /// Gets or sets the requested MIME output format (e.g., "application/json", "text/plain").
    /// </summary>
    [JsonPropertyName("responseMimeType")]
    public string ResponseMimeType { get; set; } = "application/json";

    /// <summary>
    /// Gets or sets the sampling temperature (0.0 to 2.0).
    /// </summary>
    [JsonPropertyName("temperature")]
    public double? Temperature { get; set; } = 0.2;

    /// <summary>
    /// Gets or sets Top-P nucleus sampling parameter.
    /// </summary>
    [JsonPropertyName("topP")]
    public double? TopP { get; set; }

    /// <summary>
    /// Gets or sets Top-K sampling parameter.
    /// </summary>
    [JsonPropertyName("topK")]
    public int? TopK { get; set; }

    /// <summary>
    /// Gets or sets maximum number of tokens generated in response.
    /// </summary>
    [JsonPropertyName("maxOutputTokens")]
    public int? MaxOutputTokens { get; set; }
}

/// <summary>
/// Safety setting override for content filtering.
/// </summary>
public class GeminiSafetySetting
{
    /// <summary>
    /// Gets or sets harm category (e.g., "HARM_CATEGORY_HARASSMENT", "HARM_CATEGORY_DANGEROUS_CONTENT").
    /// </summary>
    [JsonPropertyName("category")]
    public string Category { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets block threshold (e.g., "BLOCK_NONE", "BLOCK_LOW_AND_ABOVE", "BLOCK_MEDIUM_AND_ABOVE").
    /// </summary>
    [JsonPropertyName("threshold")]
    public string Threshold { get; set; } = string.Empty;
}

/// <summary>
/// Google AI Studio Gemini API Response Payload matching official REST API schema.
/// </summary>
public class GeminiApiResponse
{
    /// <summary>
    /// Gets or sets candidate response generations produced by the model.
    /// </summary>
    [JsonPropertyName("candidates")]
    public List<GeminiCandidate>? Candidates { get; set; }

    /// <summary>
    /// Gets or sets prompt feedback if prompt was blocked by safety filters.
    /// </summary>
    [JsonPropertyName("promptFeedback")]
    public GeminiPromptFeedback? PromptFeedback { get; set; }

    /// <summary>
    /// Gets or sets token usage statistics.
    /// </summary>
    [JsonPropertyName("usageMetadata")]
    public GeminiUsageMetadata? UsageMetadata { get; set; }
}

/// <summary>
/// Represents a candidate response generated by Gemini.
/// </summary>
public class GeminiCandidate
{
    /// <summary>
    /// Gets or sets the generated content turn.
    /// </summary>
    [JsonPropertyName("content")]
    public GeminiContent? Content { get; set; }

    /// <summary>
    /// Gets or sets finish reason (e.g., "STOP", "MAX_TOKENS", "SAFETY", "RECITATION").
    /// </summary>
    [JsonPropertyName("finishReason")]
    public string? FinishReason { get; set; }

    /// <summary>
    /// Gets or sets candidate index (usually 0).
    /// </summary>
    [JsonPropertyName("index")]
    public int? Index { get; set; }

    /// <summary>
    /// Gets or sets safety ratings for this candidate output.
    /// </summary>
    [JsonPropertyName("safetyRatings")]
    public List<GeminiSafetyRating>? SafetyRatings { get; set; }
}

/// <summary>
/// Safety evaluation rating for prompt or candidate response.
/// </summary>
public class GeminiSafetyRating
{
    /// <summary>
    /// Gets or sets safety harm category.
    /// </summary>
    [JsonPropertyName("category")]
    public string? Category { get; set; }

    /// <summary>
    /// Gets or sets harm probability score (e.g., "NEGLIGIBLE", "LOW", "MEDIUM", "HIGH").
    /// </summary>
    [JsonPropertyName("probability")]
    public string? Probability { get; set; }

    /// <summary>
    /// Gets or sets whether content was blocked by this category rating.
    /// </summary>
    [JsonPropertyName("blocked")]
    public bool? Blocked { get; set; }
}

/// <summary>
/// Feedback on prompt processing, including block reasons if rejected.
/// </summary>
public class GeminiPromptFeedback
{
    /// <summary>
    /// Gets or sets block reason (e.g. "SAFETY", "OTHER").
    /// </summary>
    [JsonPropertyName("blockReason")]
    public string? BlockReason { get; set; }

    /// <summary>
    /// Gets or sets safety ratings evaluated for prompt.
    /// </summary>
    [JsonPropertyName("safetyRatings")]
    public List<GeminiSafetyRating>? SafetyRatings { get; set; }
}

/// <summary>
/// Token usage statistics reported by Gemini.
/// </summary>
public class GeminiUsageMetadata
{
    /// <summary>
    /// Gets or sets prompt token count.
    /// </summary>
    [JsonPropertyName("promptTokenCount")]
    public int? PromptTokenCount { get; set; }

    /// <summary>
    /// Gets or sets candidates token count.
    /// </summary>
    [JsonPropertyName("candidatesTokenCount")]
    public int? CandidatesTokenCount { get; set; }

    /// <summary>
    /// Gets or sets total token count.
    /// </summary>
    [JsonPropertyName("totalTokenCount")]
    public int? TotalTokenCount { get; set; }
}

/// <summary>
/// DTO representing the inner structured JSON response produced by Gemini LLM.
/// </summary>
public class GeminiStructuredResponse
{
    /// <summary>
    /// Gets or sets patient-facing response text.
    /// </summary>
    [JsonPropertyName("response")]
    public string Response { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets flag indicating red-flag emergency symptoms.
    /// </summary>
    [JsonPropertyName("emergency")]
    public bool Emergency { get; set; }

    /// <summary>
    /// Gets or sets actionable practical recommendations list.
    /// </summary>
    [JsonPropertyName("recommendations")]
    public List<string> Recommendations { get; set; } = [];

    /// <summary>
    /// Gets or sets non-diagnostic follow-up questions list.
    /// </summary>
    [JsonPropertyName("followUpQuestions")]
    public List<string> FollowUpQuestions { get; set; } = [];
}
